// <auto-generated />
using KasaHesap.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KasaHesap.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KasaHesap.Models.KasaHesap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("BankaEmanet")
                        .HasColumnType("real");

                    b.Property<float>("BankaHarc")
                        .HasColumnType("real");

                    b.Property<float>("DamgaVergisi")
                        .HasColumnType("real");

                    b.Property<float>("EldeSayilanMiktar")
                        .HasColumnType("real");

                    b.Property<float>("GelirVergisi")
                        .HasColumnType("real");

                    b.Property<float>("PortalEmanet")
                        .HasColumnType("real");

                    b.Property<float>("PortalHarc")
                        .HasColumnType("real");

                    b.Property<float>("ProvizyondaBekleyenTutar")
                        .HasColumnType("real");

                    b.Property<float>("SlipToplam")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("KasaHesap");
                });
#pragma warning restore 612, 618
        }
    }
}
